//post new admin
post  http://localhost:20222/adMin/
content-type: application/json

{
    "name":"minh nhất",
    "pass":" codengu",
    "mail":"minhnhat02@gmail.com"
}
###

// get all user
get  http://localhost:20222/adMin/AllAd/




