//post new admin
post  http://localhost:20222/adMin/
content-type: application/json

{
    "name":"minh nhất",
    "pass":" codengu",
    "mail":"minhnhat02@gmail.com"
}
###
// post login
post  http://localhost:20222/adMin/Login/
content-type: application/json

{
    "mail":"minhnhat02@gmail.com",
    "pass":" codengu"
}
###
// get all user
get  http://localhost:20222/adMin/AllAd/
###
//update add
post  http://localhost:20222/adMin/UpdateAd
content-type: application/json

{
    "name":"minh nkhon",
    "pass":" codenu",
    "mail":"minhnhat02@gmail.com",
    "id":"jye35o0r5SZujcs6HyTMqGmC3qQyFC14"
}
###
// delete admin
post  http://localhost:20222/adMin/deleteAd
content-type: application/json

{
    "id":"rDHRi0ObBD0i7I78wylivtTRTEqHQJ5V"
}


