// ncreate newe produce
post  http://localhost:20222/produce/newProduce
content-type: application/json

{
    "name":"Trà Sữa Hẹ",
    "price":"20.000",
    "category":"TraSua"
}
###
// sreach for produce
get  http://localhost:20222/produce/1
Content-Type: application/json

{
    "id":"gdfg"
}

###
//update total
put  http://localhost:20222/produce/update
Content-Type: application/json

{
    "idProduce":"gdfg",
    "value":3
}
